config/routes.rb
Rails.application.routes.draw do
  # Configures Devise routes for user authentication
  devise_for :users

  # Defines the root path route ("/") to the home action in the ElectionsController
  root "elections#home"
  resources :users
  # Defines RESTful routes for elections and nested routes for candidates
  resources :elections do
    member do
      # Custom member routes for specific actions like 'end' and 'archived'
      get 'end'
      get 'archived', to: 'elections#archived'
    end

    # Nested routes for candidates within elections, including a custom route for incrementing votes
    resources :candidates do
      member do
        patch 'increment_votes'
      end
    end
  end

  # Defines a route for displaying user profiles
  # or alternatively, the following equivalent routes:
  # match 'users/:id' => 'users#show', via: :get
  # get 'users/:id' => 'users#show'
  resources :users do
    resources :elections do
      resources :candidates do
        resources :comments, only: [:create, :destroy, :update]
      end
    end
  end

end

app/views/shared/_loggednavbar.html.erb
<nav class="navbar navbar-expand-lg ">
  <!-- The opening tag for a Bootstrap navbar with a responsive design. -->

  <span class="navbar-brand non-pressable">
    <!-- The brand/logo section of the navbar. -->
    <span class="logo-text">Votifii</span>
    <!-- Display the text "Votifii" as the logo text. -->
  </span>

  <div class="collapse navbar-collapse" id="navbarNav">
    <!-- The collapsible section of the navbar. -->

    <%= link_to "Home", root_path, class: "nav-link"%>
    <!-- Display a link to the home page with the text "Home" using the link_to helper. -->

    <span class="nav-item active">
      <%= link_to "Elections", elections_path , class: "nav-link"%>
      <!-- Display a link to the elections page with the text "Elections" using the link_to helper. -->
    </span>

    <span class="nav-item active">
      <%= link_to "All Profiles", users_path , class: "nav-link"%>
      <!-- Display a link to the profiles page with the text "Profiles" using the link_to helper. -->
    </span>

    <span class="nav-item">
      <%= link_to "Hi, #{current_user.name}", user_path(current_user), class: "nav-link" %>
      <!-- Display a personalized greeting and a link to edit the user's registration information using the link_to helper. -->
    </span>

    <span class="nav-item">
      <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link"%>
      <!-- Display a link to sign out with the text "Sign Out" using the link_to helper. -->
    </span>
    <hr>
  </div>
</nav>
<!-- The closing tag for the Bootstrap navbar. -->

app/views/shared/_unloggednavbar.html.erb
<nav class="navbar navbar-expand-lg">
  <!-- The opening tag for a Bootstrap navbar with a responsive design. -->

  <span class="navbar-brand non-pressable">
    <!-- The brand/logo section of the navbar. -->
    Votifii
    <!-- Display the text "Votifii" as the brand/logo. -->
  </span>
  
  <div class="collapse navbar-collapse" id="navbarNav">
    <!-- The collapsible section of the navbar. -->

    <%= link_to "Home", root_path, class: "nav-link"%>
    <!-- Display a link to the home page with the text "Home" using the link_to helper. -->

    <span class="nav-item">
      <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
      <!-- Display a link to the sign-in page with the text "Sign In" using the link_to helper. -->
    </span>

    <span class="nav-item">
      <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
      <!-- Display a link to the sign-up page with the text "Sign Up" using the link_to helper. -->
    </span>
    <hr>
  </div>
</nav>