config/routes.rb
Rails.application.routes.draw do
  # Configures Devise routes for user authentication
  devise_for :users

  # Defines the root path route ("/") to the home action in the ElectionsController
  root "elections#home"
  resources :users
  # Defines RESTful routes for elections and nested routes for candidates
  resources :elections do
    member do
      # Custom member routes for specific actions like 'end' and 'archived'
      get 'end'
      get 'archived', to: 'elections#archived'
    end

    # Nested routes for candidates within elections, including a custom route for incrementing votes
    resources :candidates do
      member do
        patch 'increment_votes'
      end
    end
  end

  # Defines a route for displaying user profiles
  # or alternatively, the following equivalent routes:
  # match 'users/:id' => 'users#show', via: :get
  # get 'users/:id' => 'users#show'
  resources :users do
    resources :elections do
      resources :candidates do
        resources :comments, only: [:create, :destroy, :update]
      end
    end
  end

end

app/models/election.rb
class Election < ApplicationRecord
  include Visible
  belongs_to :user #Belongs to User now
  has_many :comments, dependent: :destroy
  has_many :candidates, dependent: :destroy
  VALID_STATES = ['public', 'archived']

  attribute :winner_id, :integer, default: nil
  attribute :status, :string, default: 'public'

  def archive_election
    if self.status == 'public'
      update(status: 'archived')
      puts "ARCHIVED THIS ELECTION"
    end
  end

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :status, inclusion: { in: VALID_STATES }

  
end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @users_with_elections = User.joins(:elections).distinct
    #If search, only show search
    if params[:search]
      @elections = Election.where('title LIKE ?', "%#{params[:search]}%")
    else
      @elections = Election.all
    end
  end

  def show
    @election = Election.find(params[:id])
    # @names = Candidate.all.select(:name).map(&:name)
    @candidates = @election.candidates
  end

  def new
    @election = Election.new
  end

  def create
    @election = current_user.elections.new(election_params)
    #puts "#{@election.title}, #{@election.description}, #{@election.winner_id == nil}, #{@election.status == nil}"
    if @election.save
     # puts "election created!"
      redirect_to @election
    else
      #puts "election NOT created!"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @election = Election.find(params[:id])
  end

  def update
    @election = Election.find(params[:id])
    if @election.user == current_user #Make sure they have permission
      if @election.update(election_params)
        redirect_to @election
        
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @election = Election.find(params[:id])
    if @election.user == current_user #Make sure they have permission
      @election.destroy

      redirect_to root_path, status: :see_other
    end
  end

  def find_winners(candidates)
    max_vote_count = @candidates.maximum(:voteCount)
    cands_with_max_votes = @candidates.where(voteCount: max_vote_count)
    cands_with_max_votes
  end

  def end
    @election = Election.find(params[:id])
    if @election.user == current_user #Make sure they have permission
      
      @candidates = @election.candidates
      # @winner = @candidates.max_by(&:voteCount)
      @winners = find_winners(@candidates)

      if @winners.length == 1 # important -- only archive the election if there is a clear winner!
        @election.update(winner_id: @winners.first.id)
        @election.archive_election
      else  # if more than one person, then nobody wins
        @election.update(winner_id: nil)
      end
      redirect_to election_path(@election) 
    end
  end



  private
    def election_params
      params.require(:election).permit(:title, :description)
    end
end

# test merge 

app/helpers/elections_helper.rb
module ElectionsHelper
end

app/views/elections/_form.html.erb
<%= form_with model: election do |form| %> <!-- Generate a form using the form_with helper. The form is associated with the 'election' model, which is likely an instance of the Election model in a Ruby on Rails application. -->

  <div>
    <%= form.label :title %><br> <!-- Display a label for the 'title' attribute of the 'election' model. -->
    <%= form.text_field :title %> <!-- Display a text field for the 'title' attribute, allowing users to input the title for the election. -->

    <% election.errors.full_messages_for(:title).each do |message| %> <!-- Iterate over each error message associated with the 'title' attribute of the 'election' model. -->
      <div><%= message %></div> <!-- Display each error message in a div element. This is typically used to show validation errors if there are any issues with the title attribute. -->
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br> <!-- Display a label for the 'description' attribute of the 'election' model. -->
    <%= form.text_area :description %><br> <!-- Display a text area for the 'description' attribute, allowing users to input a description for the election. -->

    <% election.errors.full_messages_for(:description).each do |message| %> <!-- Iterate over each error message associated with the 'description' attribute of the 'election' model. -->
      <div><%= message %></div> <!-- Display each error message in a div element. This is typically used to show validation errors if there are any issues with the description attribute. -->
    <% end %>
  </div>

  <div>
    <%= form.submit %> <!-- Display a submit button to submit the form. The button text will typically be the default "Submit" unless explicitly customized. -->
  </div>

<% end %> <!-- End the form_with block. -->

app/views/elections/_showCandidates.html.erb
<p> Current Candidates </p>

<% if @election.status == 'public' %>
    <h3>This election is still public!</h3>
<% else %>
    <h3>This election is now archived</h3>
<% end %>

<% @election.candidates.each do |candidate| %>
  
  <p>
    <strong> Candidate: </strong>
    <%= candidate.name %> <br>

    <strong> Description: </strong>
    <%= candidate.description%> <br>

    <strong> Votes: </strong>
    <%= candidate.voteCount %> <br>

    <strong> Id: </strong>
    <%= candidate.id %> <br>
    
  </p>
<% end %>

<% if @election.status == 'public' %>
  <%= link_to "End Election", end_election_path(@election)%>  
<% end %>

app/views/elections/_voteBallot.html.erb
<ul>
  <% if @election.status == 'public' %>
    <%= form_with(model: [@election, Candidate.new], url: increment_votes_election_candidate_path(@election), method: :patch) do |form| %>
      <select name="candidate_id">
        <% @election.candidates.each do |candidate| %>
          <option value="<%= candidate.id %>"><%= candidate.name %></option>
        <% end %>
      </select>
      <%= form.submit 'Increment Votes' %>
    <% end %>
  <% end %>
</ul>

app/views/elections/edit.html.erb
<body id="background">
    <div id="main">
		<h1 style="margin-bottom: 0;">Edit Election</h1> <!-- Display a heading indicating that the user is on the page to edit an election. -->
		<hr>
		<% if @election.user == current_user %> <!-- Check if the user attempting to edit the election is the owner of the election (the creator). -->
			<!-- If the current user is the owner, allow editing by rendering the edit form and related components. -->

			<%= render "form", election: @election %> <!-- Render a partial named "form" for editing the election. The 'election' variable is passed to the partial. -->
			<%= render "candidates/addCandidates", election: @election %> <!-- Render a partial for adding candidates to the election. -->

			<%= render "candidates/showCandidates", election: @election %> <!-- Render a partial for showing the candidates associated with the election. -->

			
		<% else %> <!-- If the current user is not the owner, display a message indicating that they do not have permission to edit the election. -->
			<h2>Cannot edit: No Permission</h2>
		<% end %>

		<%= link_to "Return", election_path(@election) %> <!-- Display a link to return to the election details page. This link points to the 'election_path' with the 'election' variable. -->

	</div>
</body>

app/views/elections/home.html.erb
<body id="background">
    <!-- The body tag represents the main content of the HTML document, and it has an id attribute set to "background." This id can be used for styling or scripting purposes. -->

    <div id="main">
      <!-- Inside the body, there is a div tag with an id attribute set to "main." This div is used to group and structure the main content of the page. -->

      <h1>Homepage</h1>
      <!-- Within the div, there is an h1 tag that represents a top-level heading. It displays the text "Homepage," indicating that the user is on the homepage of the website. -->

      <p> Welcome to Votifii </p>
      <!-- Following the heading, there is a p tag that represents a paragraph. It contains the text "Welcome to votifii," providing a welcoming message to users visiting the homepage. -->

  </div>
</body>

app/views/elections/index.html.erb
<body id="background">
  <!-- The body tag represents the main content of the HTML document, and it has an id attribute set to "background." This id can be used for styling or scripting purposes. -->

  <div id="main" onload="ListBoth()">
    <!-- Inside the body, there is a div tag with an id attribute set to "main." This div is used to group and structure the main content of the page. -->
    
    <!-- Display a link to create a new election. The link points to the new_election_path, which is typically the path for creating a new election. -->
    <h3>List of All Elections</h3>
    <%= link_to "Create New Election", new_election_path %><hr>
    <!-- Within the div, there is an h1 tag that represents a top-level heading. It displays the text "All Elections," indicating that the user is on a page showing all elections. -->

    <!--Use JS and buttons for options of listing elections-->
    <button type="button" disabled="true" id="ListBoth" onclick="ListBoth()" >List Both</button>
    <button type="button" id="ListElectionsBtn" onclick="ListElections()">List Elections</button>
    <button type="button" id="ListByOwnerBtn" onclick="ListByOwner()">List By Owner</button>

    <!--Search form-->
    <%= form_with(url: elections_path, method: :get) do |form| %>
      <%= form.text_field :search, placeholder: 'Search by name' %>
      <%= form.submit 'Search' %>
    <% end %> 
    <!--Info about the search-->
    <p style="font-size: 12px;padding: 1px;margin: 5px;">
      <%= @elections.count()%> out of <%= Election.count()%> displayed.
    </p>
    <hr>
    <div id="DisplayElections"> <!--Display all elections in a list by name, seperated if archived-->
      <ul>
        <li>Active:</li>
        <ul>
          <% @elections.order(:title).each do |election| %>
            <%if election.status == "public"%>
              <li>
                <!-- For each election, create a list item with a link to the election's details page. -->
                <%= link_to election.title, election %>
              </li>
              <% end %>
          <% end %>
        </ul>
      </ul>
      <ul>
        <li>Archived:</li>
        <ul>
          <% @elections.order(:title).each do |election| %>
            <%if election.status != "public"%>

            <li>
              <!-- For each election, create a list item with a link to the election's details page. -->
              <%= link_to election.title, election %>
            </li>
            <% end %>
          <% end %>
        </ul>
      </ul>
    </div>
    <hr>
    <div id="DisplayElectionsByOwner"> <!--Display all elections in a list by owner by name, seperated if archived-->
      <ul>
        <!-- An unordered list (ul) is used to create a list of users with their associated elections. -->
        <% @users_with_elections.order(:name).order(:email).each do |user| %>
          <!-- Iterate over each user in the collection of users with elections. -->
          <li>
            <!-- For each user, create a list item (li) to display their email address as the host. -->
            Owner: <%=  link_to user.name, user %>, <%=  link_to user.email, user %>
            <ul>
              <li>Active:</li>
              <ul>
                <% @elections.order(:title).each do |election| %>
                  <%if election.status == "public" && election.user == user %>
                    <li>
                      <!-- For each election, create a list item with a link to the election's details page. -->
                      <%= link_to election.title, election %>
                    </li>
                    <% end %>
                <% end %>
              </ul>
            </ul>
            <ul>
              <li>Archived:</li>
              <ul>
                <% @elections.order(:title).each do |election| %>
                  <%if election.status != "public" && election.user == user %>

                  <li>
                    <!-- For each election, create a list item with a link to the election's details page. -->
                    <%= link_to election.title, election %>
                  </li>
                  <% end %>
                <% end %>
              </ul>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
    <hr>
  </div>
</body>

<script>
  //Turns on or off buttons and elements
  function ListByOwner() {
    document.getElementById("ListElectionsBtn").disabled = false;
    document.getElementById("ListByOwnerBtn").disabled = true;
    document.getElementById("ListBoth").disabled = false;
    document.getElementById("DisplayElections").style.display="none";
    document.getElementById("DisplayElectionsByOwner").style.display="block";
  }

  function ListElections() {
    document.getElementById("ListElectionsBtn").disabled = true;
    document.getElementById("ListByOwnerBtn").disabled = false;
    document.getElementById("ListBoth").disabled = false;
    document.getElementById("DisplayElections").style.display="block";
    document.getElementById("DisplayElectionsByOwner").style.display="none";
  }

  function ListBoth() {
    document.getElementById("ListElectionsBtn").disabled = false;
    document.getElementById("ListByOwnerBtn").disabled = false;
    document.getElementById("ListBoth").disabled = true;
    document.getElementById("DisplayElections").style.display="block";
    document.getElementById("DisplayElectionsByOwner").style.display="block";
  }
</script>

app/views/elections/new.html.erb
<body id="background">
    <!-- The body tag represents the main content of the HTML document, and it has an id attribute set to "background." This id can be used for styling or scripting purposes. -->

    <div id="main">
        <!-- Inside the body, there is a div tag with an id attribute set to "main." This div is used to group and structure the main content of the page. -->

        <h1>New Election</h1>
        <!-- Within the div, there is an h1 tag that represents a top-level heading. It displays the text "New Election," indicating that the user is on the page for creating a new election. -->

        <%= render "form", election: @election, id: @election.id %>
        <!-- Render a partial named "form" for creating a new election. The 'election' variable is passed to the partial, representing the instance of the Election model being created. The 'id' attribute is also passed, possibly for customization purposes within the form. -->

    </div>
</body>

app/views/elections/show.html.erb
<body id="background">
    <div id="main">


  <h1><%= @election.title %></h1>
  <% if @election.winner_id.present? %>
    <hr/>
    <h4><strong>Winner:</strong></h4>
    <% @winner=Candidate.find(@election.winner_id) %>
    <p><em><%= @winner.name %></em> with <em><%= @winner.voteCount %> votes!</em></p>
    <p><strong>Description:</strong> <%= @winner.description %>
    <hr/>
  <% else %>
    <h3> No Winner </h3>
  <% end %>

  <p><%= @election.description %></p>

  <!--If current_user is election.user, show options-->
  <% if @election.user == current_user %> 
    <p>Options: <% if @election.status == "public" %> <%= link_to "End", end_election_path(@election) %> | <%= link_to "Edit", edit_election_path(@election) %> | <% end %> <%= link_to "Delete", election_path(@election), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                      } %>
    </p>
  <% end %>


  <% if @election.candidates.count() == 0 %>
      <div>
          You currently have no candidates added. 
          <%= link_to "Add candidates here", edit_election_path(@election) %>
     </div>
  <% end %>

   <% if @election.candidates.count() != 0 %>
      <div>
        <%= render 'candidates/voteBallot', election: @election %>
     </div>
  <% end %>
  <h4> Current Candidates </h4>
  <hr>
    <div>
      <span class="comment-content">Enable Comment Editing</span>
      <!--Cool looking switch, enables editing-->
      <label class="switch">
        <input type="checkbox" checked="true" id="EditingEnabled" onchange="toggleCommentEdit()">
        <span class="slider round"></span>
      </label>
    </div>
  <hr>
  <% @election.candidates.order(:name).each do |candidate| %>
    <p>

      
      <strong> <%= candidate.name %> </strong> <br> 
      <%= image_tag candidate.image_link, style: 'max-width: 150px; max-height: 150px;' %> <br>
      <strong> Description: </strong>
      <%= candidate.description%> <br>

      <strong> Votes: </strong>
      <%= candidate.voteCount %> <br>

      <strong> Speech: </strong>
      <%= simple_format(candidate.speech) %> <br>

  

    <% candidate.comments.each do |comment| %>
      <li>
        <strong><%= link_to comment.user.name, comment.user,{:style=>'text-decoration: none;'}%>:</strong>
        <!--In short, this displays comments, then displays edit and delete buttons--> 
        <span class="comment-content"><%= comment.content %></span>
        <div class="EditAndDeleteComments", style="display: block;">
          <% if current_user == comment.user %>
            <%= form_with(model: [current_user, @election, candidate, comment], method: :patch, url: user_election_candidate_comment_path(current_user, @election, candidate, comment), data: { confirm: 'Are you sure?' }) do |form| %>
              <%= form.text_field :content %>
              <%= form.submit 'Update Comment' %>
            <% end %>
          <% end %>
          <% if current_user == comment.user  || current_user == @election.user %> <!--Election Owner can delete-->
            <%= form_with(model: [current_user, @election, candidate, comment], method: :delete, url: user_election_candidate_comment_path(current_user, @election, candidate, comment), data: { confirm: 'Are you sure?' }) do |form| %>
              <%= form.submit 'Delete Comment' %>    
            <% end %>
          <% end %>
       </div>
      </li>
    <% end %>
    <hr>
    <!--Creates a Comment-->
    <%= form_with(model: [current_user, @election, candidate, Comment.new], url: user_election_candidate_comments_path(current_user, @election.id, candidate.id), method: :post) do |form| %>
      <%= form.hidden_field :election_id, value: @election.id %>
      <%= form.text_area :content, placeholder: 'Add a comment' %>
      <%= form.submit 'Post Comment' %>
    <% end %>
      <hr>
      
    </p>
    </p>
  <% end %>
  </div>
</body>

<script>
  //Enable/Disable comment edit form
  function toggleCommentEdit() {
     if (document.getElementById("EditingEnabled").checked == true) {
      const collection = document.getElementsByClassName("EditAndDeleteComments");
      for (var i = 0; i < collection.length; i++) { 
        collection[i].style.display="block";
      }
     }
     else {
        const collection = document.getElementsByClassName("EditAndDeleteComments");
      for (var i = 0; i < collection.length; i++) { 
        collection[i].style.display="none";
      }
     }
      
  }
</script>

<style>
  h4 {
    font-size: 14px;
    margin-bottom: 4px;
  }
  /* Removes the break between comment and editing and delete form
  Add appropriate styling to position the form elements */
  .comment-content {
    margin-right: 10px; /* Adjust as needed */
    display: inline-block;
  }

  /* Ensure the form elements are displayed inline */
  form {
    display: inline-block;
  }
  /*For the cool looking switch*/
  .switch {
    position: relative;
    display: inline-block;
    width: 60px;
    height: 34px;
  }

  .switch input { 
    opacity: 0;
    width: 0;
    height: 0;
  }

  .slider {
    position: absolute;
    cursor: pointer;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #ccc;
    -webkit-transition: .4s;
    transition: .4s;
  }

  .slider:before {
    position: absolute;
    content: "";
    height: 26px;
    width: 26px;
    left: 4px;
    bottom: 4px;
    background-color: white;
    -webkit-transition: .4s;
    transition: .4s;
  }

  input:checked + .slider {
    background-color: #2196F3;
  }

  input:focus + .slider {
    box-shadow: 0 0 1px #2196F3;
  }

  input:checked + .slider:before {
    -webkit-transform: translateX(26px);
    -ms-transform: translateX(26px);
    transform: translateX(26px);
  }

  /* Rounded sliders */
  .slider.round {
    border-radius: 34px;
  }

  .slider.round:before {
    border-radius: 50%;
  }
</style>