config/routes.rb
Rails.application.routes.draw do
  # Configures Devise routes for user authentication
  devise_for :users

  # Defines the root path route ("/") to the home action in the ElectionsController
  root "elections#home"
  resources :users
  # Defines RESTful routes for elections and nested routes for candidates
  resources :elections do
    member do
      # Custom member routes for specific actions like 'end' and 'archived'
      get 'end'
      get 'archived', to: 'elections#archived'
    end

    # Nested routes for candidates within elections, including a custom route for incrementing votes
    resources :candidates do
      member do
        patch 'increment_votes'
      end
    end
  end

  # Defines a route for displaying user profiles
  # or alternatively, the following equivalent routes:
  # match 'users/:id' => 'users#show', via: :get
  # get 'users/:id' => 'users#show'
  resources :users do
    resources :elections do
      resources :candidates do
        resources :comments, only: [:create, :destroy, :update]
      end
    end
  end

end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :election, optional: true
  after_initialize :default_values
  has_many :comments, dependent: :destroy
  # has_one_attached :profile_image

  validates :speech, presence: true

private
  def default_values
    self.voteCount ||= 0
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

    before_action :authenticate_user!, except: :increment_votes
    
    def create
        @election = Election.find(params[:election_id])

        if @election.user == current_user #Make sure they have permission
            #@election.update_attribute(:candidateCount, @election.candidateCount + 1)

            @candidate = @election.candidates.create(candidate_params)
            #If Image Link was empty, give a default one
            if @candidate.image_link.length() == 0
                @candidate.image_link = render_pic
                @candidate.save
            end

            redirect_back(fallback_location: root_path)
        end
    end

    def update
        @election = Election.find(params[:election_id])
        @candidate = @election.candidates.find(params[:id])
        if @election.user == current_user #Make sure they have permission
            #@election.update_attribute(:candidateCount, @election.candidateCount + 1)
            @candidate.update(candidate_params)
            redirect_to edit_election_path(@election)
        end
    end

    def destroy
        @election = Election.find(params[:election_id])
        if @election.user == current_user #Make sure they have permission
            #@election.update_attribute(:candidateCount, @election.candidateCount - 1)
            @candidate = @election.candidates.find(params[:id])
            @candidate.destroy
            redirect_to edit_election_path(@election), status: :see_other
        end
    end
    def show
        @election = Election.find(params[:election_id])
        @candidate = @election.candidates.find(params[:candidate_id])
    end
    def checkInput
        @candidate = Election.find(params[:commit])
        @candidate.description = "hello "
    end

    def increment_votes #Increments
        @election = Election.find(params[:election_id])
        if params[:candidate_id] != "-1" #If -1, means abstain
            candidate = Candidate.find(params[:candidate_id]) #Takes candidate_id from form
    
            if !candidate.voters.include?(current_user.id) #If current_user hasn't voted for this candidate
                candidate.increment(:voteCount) #Instead of increment, can call method declared in candidate.rb
                @election.candidates.each { |otherCandidate| # If current_user has voted for someone else, prevent them
                    if otherCandidate != candidate && otherCandidate.voters.include?(current_user.id)
                        otherCandidate.decrement(:voteCount)
                        # Add the current user to the voters array
                        otherCandidate.voters.delete(current_user.id)
                        # Save the record to persist the changes
                        otherCandidate.save 
                    end
                }
                #Add current user to the record
                # Add the current user to the voters array
                candidate.voters << current_user.id
                # Save the record to persist the changes
                candidate.save 
                
            end
        else
            @election.candidates.each { |candidate| # If current_user has voted for someone else, remove them
                if candidate.voters.include?(current_user.id)
                    candidate.decrement(:voteCount)
                    # Add the current user to the voters array
                    candidate.voters.delete(current_user.id)
                    # Save the record to persist the changes
                    candidate.save 
                end
            }
        end
        redirect_to election_path(@election)
    end

private
    def candidate_params
        params.require(:candidate).permit(:name, :description, :image_link, :speech)
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_addCandidates.html.erb
<hr>
<h3 style="margin-bottom: 0;"> Add Candidate </h3>
<%= form_with model: [ @election, @election.candidates.build ] do |form| %>
    <div style="font-size: 15px">
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <%= form.label :speech %><br>
    <%= form.text_area :speech%><br>
    <%= form.label :"Image Link" %><br>
    <%= form.text_field :image_link %><br>
  </div>
    <%= form.submit %>
<% end %>
<hr>
<style>
  p {
    font-size: 15px;
    margin-top: 0;
  }


</style>

app/views/candidates/_showCandidates.html.erb
<body>

  <h3 style="margin-bottom: 0;"> Current Candidates </h3>

  <% if @election.candidates.count() == 0 %>
      <div>
          <p> You currently have no candidates added. </p>
     </div>
  <% end %>

  <div>
    <span class="candidate-content">Enable Candidate Editing</span>
    <!--Cool looking switch, enables editing-->
    <label class="switch">
      <input type="checkbox" checked="true" id="EditingEnabled" onchange="toggleCandidateEdit()">
      <span class="slider round"></span>
    </label>
  </div>

  <div>
    <% @election.candidates.order(:name).each do |candidate| %>
      <div class="DisplayCandidate" style="display: none; font-size: 15px">

          
          <strong> <%= candidate.name %></strong>  <br>
          <%= image_tag candidate.image_link, style: 'max-width: 150px; max-height: 150px;' %><br>
          <strong> Description: </strong>
          <%= candidate.description%> <br>

          <strong> Speech: </strong>
          <%= simple_format(candidate.speech)  %><br>

          <strong> Votes: </strong>
          <%= candidate.voteCount %> <br>
     </div>
      
      <div class="EditAndDeleteCandidate">
        
          <%= form_with model: [candidate.election, candidate ] do |form| %>

              <div style="font-size: 15px;"><%= form.label :name %><br>
              <%= form.text_field :name %><br>

              <%= form.label :description %><br>
              <%= form.text_area :description %><br>

              <%= form.label :speech %><br>
              <%= form.text_area :speech%><br>

              <%= form.label :"Image Link" %><br>
              <%= form.text_field :image_link%><br>
              </div>
              <div style="margin-right: 0;padding-right: 0;">
              <%= form.submit %>
              
          <% end %>
        
          <%= form_with(model: [candidate.election, candidate ], method: :delete, url: election_candidate_path(@election, candidate), data: { confirm: 'Are you sure?' }) do |form| %>
            <%= form.submit 'Delete ' + candidate.name %>    
          <% end %>
        </div>
      </div>
      <hr>
    <% end %>
  </div>

</body>
<script>
  //Enable/Disable comment edit form
  function toggleCandidateEdit() {
     if (document.getElementById("EditingEnabled").checked == true) {
      const collection = document.getElementsByClassName("EditAndDeleteCandidate");
      for (var i = 0; i < collection.length; i++) { 
        collection[i].style.display="block";
      }
      const collection2 = document.getElementsByClassName("DisplayCandidate");
      for (var i = 0; i < collection2.length; i++) { 
        collection2[i].style.display="none";
      }
     }
     else {
        const collection = document.getElementsByClassName("EditAndDeleteCandidate");
      for (var i = 0; i < collection.length; i++) { 
        collection[i].style.display="none";
      }
      const collection2 = document.getElementsByClassName("DisplayCandidate");
      for (var i = 0; i < collection2.length; i++) { 
        collection2[i].style.display="block";
      }
     }
      
  }
</script>

<style>
  h4 {
    font-size: 14px;
    margin-bottom: 4px;
  }
  /* Removes the break between comment and editing and delete form
  Add appropriate styling to position the form elements */
  .candidate-content {
    margin-right: 10px; /* Adjust as needed */
    display: inline-block;
    font-size: 15px;
  }

  /* Ensure the form elements are displayed inline */
  form {
    display: inline-block;
  }
  /*For the cool looking switch*/
  .switch {
    position: relative;
    display: inline-block;
    width: 42px;
    height: 24px;
  }

  .switch input { 
    opacity: 0;
    width: 0;
    height: 0;
  }

  .slider {
    position: absolute;
    cursor: pointer;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #ccc;
    -webkit-transition: .4s;
    transition: .4s;
  }

  .slider:before {
    position: absolute;
    content: "";
    height: 18px;
    width: 18px;
    left: 2px;
    bottom: 3px;
    background-color: white;
    -webkit-transition: .4s;
    transition: .4s;
  }

  input:checked + .slider {
    background-color: #2196F3;
  }

  input:focus + .slider {
    box-shadow: 0 0 1px #2196F3;
  }

  input:checked + .slider:before {

    transform: translateX(20px);
  }

  /* Rounded sliders */
  .slider.round {
    border-radius: 17px;
  }

  .slider.round:before {
    border-radius: 50%;
  }
</style>

app/views/candidates/_voteBallot.html.erb
<ul>

    <% if @election.status == 'public' %> <!-- Check if the election status is set to 'public' -->
      <%= form_with(model: [@election, Candidate.new], url: increment_votes_election_candidate_path(@election), method: :patch) do |form| %> <!-- Create a form using the form_with helper for updating candidate votes via a patch request -->
        <select name="candidate_id"> <!-- Create a dropdown menu for selecting a candidate -->
          <% @election.candidates.order(:name).each do |candidate| %> <!-- Iterate through the election's candidates, ordering them by name -->
            <%if !candidate.voters.include?(current_user.id)%> <!--Prevent from voting if voted for that candidate-->
              <option value="<%= candidate.id %>"><%= candidate.name %></option> <!-- Create an option for each candidate in the dropdown menu -->
            <% end %>
          <% end %>
          <option value="<%= -1 %>">Abstain</option> <!--Option to abstain, candidate_id=-1-->
        </select>
        <%= form.submit 'Vote' %> <!-- Display a submit button labeled 'Increment Votes' for submitting the form -->
      <% end %>
    <% end %>
</ul>